from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('roles/', views.roles, name='roles'),
    path('signin/', views.signin, name='signin'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('join/', views.join, name='join'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('mission/', views.mission, name='mission'),
    path('vision/', views.vision, name='vision'),
    path('training/', views.training, name='training'),
    path('user-dashboard/', views.user_dashboard, name='user_dashboard'),
    path('report-waste/', views.report_waste, name='report_waste'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('volunteer-dashboard/', views.volunteer_dashboard, name='volunteer_dashboard'),
    path('organize-events/', views.organize_events, name='organize_events'),
    path('verify-reports/', views.verify_reports, name='verify_reports'),
    path('community-management/', views.community_management, name='community_management'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-reports/', views.admin_reports, name='admin_reports'),
    path('admin-users/', views.admin_users, name='admin_users'),
    path('assign-volunteer/', views.assign_volunteer, name='assign_volunteer'),
    path('accept-report/', views.accept_report, name='accept_report'),
    path('reject-report/', views.reject_report, name='reject_report'),
    path('complete-report/', views.complete_report, name='complete_report'),
    path('crew-dashboard/', views.crew_dashboard, name='crew_dashboard'),
    path('crew-update-status/', views.crew_update_status, name='crew_update_status'),
    path('admin-crew/', views.admin_crew, name='admin_crew'),
    path('admin-crew-add/', views.admin_crew_add, name='admin_crew_add'),
    path('admin-crew-edit/', views.admin_crew_edit, name='admin_crew_edit'),
    path('admin-crew-toggle/', views.admin_crew_toggle, name='admin_crew_toggle'),
    path('admin-crew-reset-password/', views.admin_crew_reset_password, name='admin_crew_reset_password'),
    path('join-event/', views.join_event, name='join_event'),
    path('admin-event-participants/', views.admin_event_participants, name='admin_event_participants'),
    path('admin-approve-participant/', views.admin_approve_participant, name='admin_approve_participant'),
    path('get-event-participants/', views.get_event_participants, name='get_event_participants'),
    path('get-event-details/', views.get_event_details, name='get_event_details'),
    path('delete-event/', views.delete_event, name='delete_event'),
    path('delete-user/', views.delete_user, name='delete_user'),
    path('delete-crew-member/', views.delete_crew_member, name='delete_crew_member'),
    path('delete-participant/', views.delete_participant, name='delete_participant'),
    path('delete-report/', views.delete_report, name='delete_report'),
    path('admin-dashboard-simple/', views.admin_dashboard_simple, name='admin_dashboard_simple'),
    path('system-analytics/', views.system_analytics, name='system_analytics'),
    path('mark-message-read/', views.mark_message_read, name='mark_message_read'),
    path('search-reports/', views.search_reports, name='search_reports'),
    path('search-events/', views.search_events, name='search_events'),
    path('search-users/', views.search_users, name='search_users'),
    path('search-messages/', views.search_messages, name='search_messages'),
    path('redeem-points/', views.redeem_points, name='redeem_points'),

]