# Generated by Django 4.2.7 on 2025-09-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_event_crewmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
