# Generated by Django 5.2.6 on 2025-09-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_eventparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='photo_timestamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
